Algoritmo "exercicio1"

Var
   numeroA: real
   numeroB: real
   numeroC: real
   soma: real


Inicio
      escreva("Digite o primeiro valor: ")
      leia(numeroA)

      escreva("Digite o segundo valor: ")
      leia(numeroB)
      
      escreva("Digite o terceiro valor: ")
      leia(numeroC)
      
      soma <- numeroA + numeroB + numeroC
      
      escreva("A soma dos valores é: ")
      escreva(soma)


Fimalgoritmo